# Generated by Django 3.1.4 on 2020-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_auto_20201218_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='new'),
        ),
    ]
