# Generated by Django 3.1.4 on 2020-12-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_auto_20201219_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
