# Generated by Django 3.1.4 on 2020-12-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_auto_20201219_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
