# Generated by Django 3.1.4 on 2020-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_auto_20201219_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fullfilled'), ('canceled', 'Canceled')], default='new', max_length=20),
        ),
    ]
